### ISSUE TITLE
calendar.view.MainContainer: regression bug => the DateSelector jumps from null to today to july 2023 

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#4915] opened 2023-09-15 09:18 UTC
this includes an animation, which was not there earlier.

not sure yet, how the `new Date()` gets into `currentDate` of the MainViewModel.

**Comment by Kwamecody** [comment] 2023-09-27 07:25
can you please assign me this task?

**Comment by tobiu** [comment] 2023-09-27 16:00
hi @Kwamecody,

sure, if you want to give it a try. the process is to create a fork and send a pull request with related changes. feel free to jump into the slack channel, in case you have not done so already.

best regards!

**Comment by Kwamecody** [comment] 2023-09-27 19:09
noted with thanks.

**Comment by Kwamecody** [comment] 2023-09-29 21:30
Hello @tobiu ,

I trust this message finds you well. I wanted to provide you with a transparent update on the progress of the calendar component bug investigation.

I've conducted a comprehensive review of all methods within the **`MainContainer `** that set or update the date. Additionally, I've closely examined portions of the code where date manipulation occurs, especially focusing on the connection between the model's **`currentDate`** and the date selector in **`MainContainer`**.

Despite multiple attempts and thorough analysis, I'm currently facing challenges in pinpointing the root cause of the issue that results in the date jumping from `None to today to July 2023`.

Regrettably, at this point,I believe it would be ideal to consider reassigning the task to another person.

Thank you.

**Comment by tobiu** [comment] 2023-09-30 11:14
no worries, this one was non-trivial. i got a fix running locally now.

**Closed** 2023-09-30 11:16 UTC
Labels: bug
